README.md
bin/studio-common
dot-studio/studio_setup

This helper allows users to ci-studio-common to quickly clone a copy of a provided helper to their source directory and modify it to fit their needs.

Add the 'clone_function' helper

---

dot-studio/networking

Now every time we add an entry to the `/etc/hosts` we are appending a
carrier return at the beginning of the line, we have found a problem
where when the file has not a new line we where appending it at the end
of the last entry like:
```
127.0.0.1 localhost 2.3.4.5 new_host
```
Now we will have:
```
127.0.0.1 localhost
2.3.4.5 new_host
```

FIX: configure_host adds extra line to /etc/hosts

---

bin/hab-verify

If we don't set this up, anything that we do within the shell script won't explode. We want to explode since we have requirements that if they are not fulfilled we should not proceed any further.

Make sure that we fail if something fails

---

.bldr.toml

This will set us up for a near future when we'll leverage the Habitat Build Service. Rather than building on every push to master, we'll rely on Expeditor to trigger the builds as part of it's action set. 

Add bldr.toml that disables auto builds

---

CHANGELOG.md

I merged a test change to test Expeditor, but I forgot to skip the changelog update.

Remove unnecessary release from CHANGELOG

---

dot-studio/svc_coord

Wait until the provided URL response with Status Code: 200
Example:
```
wait_for_ok_response localhost:1234/version
=> Waiting for 'localhost:2192/version' to response OK (200). [Got:404]
=> Waiting for 'localhost:2192/version' to response OK (200). [Got:404]
=> Waiting for 'localhost:2192/version' to response OK (200). [Got:404]
```

Add wait_for_ok_response

---

dot-studio/golang

First three golang studio helpers:
* `setup_go_workspace` - Setup the Go Workspace. (requires $pkg_scaffolding to be set)
* `install_go_tool`    - Install the specified go tool(s).
* `go_build`           - Builds the $pkg_name binary. (a.k.a. go build)

Golang studio helpers

---

bin/studio-common

This change fixes a problem where if you have a `/src/.studio` directory but it is empty (no files in it) you will see this error:
```
bash: /src/.studio/*: No such file or directory
```

Check if /src/.studio/ is not empty

---

dot-studio/golang

I missed adding these exports in the `go_build` helper method.

Fix go_build to setup GO_LDFLAGS

---

dot-studio/svc_coord

Adding wait_or_fail functions to exit out of tests if the service never
starts. We are finding that when some services do not start correctly
the wait_for methods are never ending. These new functions will allow
the wait to fail after a set amount of time.
Signed-off-by: Lance Finfrock <lfinfrock@chef.io>

Adding wait_or_fail Functions

---

dot-studio/svc_coord

The wait_for_port_to_listen has been updated on know projects. Removing
the code in the function.
issue: https://github.com/chef/ingest-service/issues/139
Signed-off-by: Lance Finfrock <lfinfrock@chef.io>

Deprecating wait_for_port_to_listen Function

---

bin/hab-verify

This PR fixes the problem where the `hab-verify in-studio CMD` command won't run any command inside the studio since we moved its functionality into a function called `in_studio` and now we are passing the command to run as a sub-parameter to that function. Now we are using the right parameter (first argument`$1`) and also verifying that it is not empty.
Also put some extra comments explaining what's going on. 

[BUG-FIX] Correct arguments for in_studio func

---

dot-studio/protobuf

We had errors in all our projects since we were trying to install
`protoc-gen-lint` from our `vendor/` directory:
```
=> Installing Go Tool 'protoc-gen-lint'
can't load package: package
github.com/chef/automate-gateway/vendor/github.com/ckaznocha/protoc-gen-lint: cannot find package "github.com/chef/automate-gateway/vendor/github.com/ckaznocha/protoc-gen-lint" in any of:
/hab/pkgs/core/go/1.9.2/20171026082055/src/github.com/chef/automate-gateway/vendor/github.com/ckaznocha/protoc-gen-lint (from $GOROOT)
/hab/cache/src/go/src/github.com/chef/automate-gateway/vendor/github.com/ckaznocha/protoc-gen-lint (from $GOPATH)
bash: scripts/grpc.sh: /usr/local/bin/bash: bad interpreter: No such file or directory
```
This if fixing the problem by only installing it if we actually need it,
and if we …

Fix compile_go_protobuf; install lint plugihn from internet

---

dot-studio/protobuf

Some services might not leverage a grpc-gateway, lets not install plugins we don't use.

Install protobuf plugins only if needed

---

dot-studio/protobuf

I was seeing this error every time we enter our studios:
```
+++ source /hab/pkgs/chef/ci-studio-common/0.1.43/20171115201623/dot-studio/protobuf
++++ document compile_go_protobuf
+++++ go env GOPATH
bash: go: command not found
```
This is the fix! :)

Avoid running go env $GOPATH from docs

---

dot-studio/golang

Without this change when running a 'go build' the below warning would be
displayed
```
/tmp/go-link-561868995/000000.o: In function
`_cgo_b0c710f30cfd_C2func_getaddrinfo':
/tmp/go-build/net/_obj/cgo-gcc-prolog:46: warning: Using 'getaddrinfo'
in statically linked applications requires at runtime the shared
libraries from the glibc version used for linking
```
Even though the two lines added to the go_build function are being called in the
'go_static_linked_flags' function, the 'CC' variable is not being
exported publicly because of the the way it is being called.
resolves: https://github.com/chef/converge-service/issues/253
Signed-off-by: Lance Finfrock <lfinfrock@chef.io>

Static Linking Warning Fix

---

dot-studio/golang

We have detected that we still have warnings with other go commands,
this PR fixes all warnings from all go comands.
Follow up from: 
- https://github.com/chef/converge-service/issues/253
- https://github.com/chef/ci-studio-common/pull/62

Fix all static linking warnings

---

bin/run-if-changed

The go language in Travis actually symlinks code into the GOPATH. By
cd-ing out of the GOPATH, we could be causing unknown behavior. This
change just determines where we are starting out. This has the added
benefit of expanding support outside of Travis by no longer depending
on Travis variables.

Use 'pwd' instead of Travis build directory to determine location

---

dot-studio/golang

I kept seeing this in our studios:
```
ALIASES:
co     Alias for: compile_go_protobuf
de     Alias for: dep_ensure
egw    Alias for: enter_go_workspace
gb     Alias for: go_build
cat: /tmp/aliases/go_debug_attach_running_service: No such file or directory
Alias for: go_debug_attach_running_service
cat: /tmp/aliases/go_debug_attach_to_pid: No such file or directory
Alias for: go_debug_attach_to_pid
gdm    Alias for: go_debug_mode
gds    Alias for: go_debug_server
sl     Alias for: sup-log
sr     Alias for: sup-run
st     Alias for: sup-term
```

Fix typos in aliases

---

dot-studio/golang

Add a parameter on the go_build function to specify where the built binary will be located.
Signed-off-by: Lance Finfrock <lfinfrock@chef.io>

Specify Output Location for go_build

---

dot-studio/golang

this ensures that when we build our tooling in CI that we
only fetch deps that are specified in the lockfile and do
not update libraries that haven't been explicitly checked
in during development.
Signed-off-by: Stephen Delano <stephen@chef.io>

golang: run `dep ensure -vendor-only`

---

README.md
bin/hab-origin
install.sh

This PR is a **fix and a new feature.**
**FIX**: When an origin has more than one public key listed we need to use the last entry since that is the active one. This is important to check with citadel the right `key_revision`.
**FEATURE**: I was trying to test this code living in a branch without merging to master and I wondered: How can I do this? Well, with the commit https://github.com/chef/ci-studio-common/pull/78/commits/f1e59f704884baf6aefa4ba566e0369171edc090 you can now run the following command to install `ci-studio-common` from this branch: (as an example)
```
curl https://raw.githubusercontent.com/chef/ci-studio-common/master/install.sh | bash -s -- afiune/fix-hab-origin
```

Fix hab-origin with multiple pub-keys & Enable installation from a dev branch

---

dot-studio/golang

This commit is updating the `dep_ensure` helper to only run when the
vendor/ directory is missing. Think about this helper as a safety hook
that, when you call it, it will ensure you have your dependencies, but
if you already have them, then it won't modify them. If you need to
actually update your Go dependencies you have to run `dep ensure`
manually.
Tested this locally, if we do NOT have a `vendor/` dir:
```
=> Configuring Go Workspace. [please wait]
=> Available scaffolding variables:
$scaffolding_go_gopath        - /hab/cache/src/go
$scaffolding_go_workspace_src - /hab/cache/src/go/src
$scaffolding_go_pkg_path      - /hab/cache/src/go/src/github.com/chef/a2
=> Installing Go Tool 'dep'
=> Executing Go dependency solver (dep ensure -vendor-only)
=> Executing Go build
=> Reloading …
```

dep_ensure runs only when vendor/ is missing

---

bin/studio-common

By the time the version check occurs, a version of `hab` other than `required_version` has been installed. Installing the correct version on the system won't change what's installed in the studio, so it needs to be removed.

Update version help to include `hab studio rm`

---

bin/studio-common

Instead of using `hab pkg path` to determine the path to the dot-studio
directory, find it relative to the location of the studio-common script. This
facilitates testing local changes to ci-studio-common without having to
upload and promote habitat packages.

Allow for local development by sourcing dot-studio files with relative path

---

dot-studio/protobuf

This is documentation via PR about a problem in the current studio
setup.  Because many of our builds use static linking, the A2 studio
sets GO_STATIC_BIN=true which ends up exporting CC as musc-gcc.
This breaks pretty much any go compiles that /isn't/ statically
linked.
I fixed this for deployment service by moving us to use static
linking, but others are still seeing it compiling protobufs because
some protobuf compiles require additional go compilations.
I think the *complete* fix is to make sure that variables like CC
aren't leaked into the environment and that any build scripts are set
up to modify their own environment as needed.

Unset CC during protobuf compile

---

dot-studio/hab_toolchain

We now set -u in a number of places so it isn't safe to refer to
unbound variables anywhere.

Don't use unbound variables

---

dot-studio/hab_toolchain

There are many places in the A2 .studiorc and friends that we use
`install_if_missing` deep inside of functions and to wrap other
tools. We rely on `install_if_missing` to work silently, because
we rely on having the ability to parse the output of the tools that
it installs. We need to make `install_if_missing` quiet again.
This change landed in stable today and has caused multiple things
to break:
https://github.com/chef/ci-studio-common/commit/4aab13426154cb2afff21536d0973685caa83cfd
We've already shipped one fix to A2, but it looks like this is the
root cause so it's better to just make this silent like it's always
been than to play whack-a-mole for every place we use it.
Signed-off-by: Stephen Delano <stephen@chef.io>

install_if_missing, just do it quietly

---

dot-studio/svc_coord

```
[8][default:/src:0]# wait_for_success asdfasdf
=> Waiting for 'asdfasdf' to succeed. (0 of 60)
=> Waiting for 'asdfasdf' to succeed. (1 of 60)
=> Waiting for 'asdfasdf' to succeed. (2 of 60)
=> ERROR: Command 'asdfasdf' never succeeded in 3 seconds.
[18][default:/src:1]# echo $?
1
[9][default:/src:130]# wait_for_success ls
[13][default:/src:0]# echo $?
0
```

Fix wait_for_success to wait for success and not failure

---

.expeditor/config.yml

This config ensures we promte to `dev` after  we successfully build the Habitat package.
More details on this auto-promotion logic can be found at:
https://expeditor.chef.io/docs/integrations/habitat/
Signed-off-by: Seth Chisamore <schisamo@chef.io>

Ensure Hab packages are promoted to `dev`

---

dot-studio/studio_setup

With the new version of habitat, we no longer use the `.secrets` pattern but instead we use the proper habitat way to share secrets through env variables, in our case we use `HAB_STUDIO_SECRET_GITHUB_TOKEN` that needs to be exported before entering the studio. 
This PR is updating the error message to give better instructions of what needs to happen to fix the problem.

Update generate_netrc_config error message

---

dot-studio/studio_setup

Some software, such as libraries used by oc-chef-pedant will fail if the file is not `0600`

Enforce correct permissions on netrc

---

bin/studio-common
habitat/plan.sh

This PR fixes the following error message when you enter the studio and source ci-studio-common:
```
✓ Installed chef/ci-studio-common/1.1.19/20180911215228
★ Install of chef/ci-studio-common/1.1.19/20180911215228 complete with 1 new packages installed.
/hab/pkgs/chef/ci-studio-common/1.1.19/20180911215228/bin/studio-common: line 31: curl: command not found
WARNING: Version '0.59.0' of Habitat has not been fully tested for compatibility with ci-studio-common.
Please consider exiting the studio, running:
=> hab studio rm
to remove the studio, and then
=> curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash -s -- -v
Helpers from ci-studio-common and your local .studio folder have been added. Run 'describe' for more information.
```

Install curl command before using it

---

dot-studio/svc_coord

Helper function to wait for a Habitat service (hab svc) to be loaded by the Habitat Supervisor.
Arguments:
@(arg:1) PKG_IDENT A Habitat package identifier (ex: core/redis)
@(arg:2) Number of seconds to wait before returning 1. (default: 60 seconds)
@(arg:3) Wheter or not this process runs silently
Example:
```
wait_or_fail_for_svc_to_load $HAB_ORIGIN/redis 30
```

New wait_or_fail_for_svc_to_load helper

---

dot-studio/svc_coord

Helper function to ask the Habitat supervisor if a service is running or not.
Arguments:
@(arg:1) PKG_IDENT A Habitat package identifier (ex: core/redis)
Example:
```
svc_running $HAB_ORIGIN/redis
rc=$?
if [[ $rc == 0 ]]; then
else
fi
```

New svc_running helper

---

dot-studio/golang
dot-studio/protobuf

Before we where only installing go tools from the vendor/ directory,
this PR is now adding the ability to install go tools NOT from a vendor/
dir.
As an example of the new usage: Install a number of go tools from your vendor/ directory
```
local proto_go_tools=(
github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
github.com/golang/protobuf/protoc-gen-go
)
GO_TOOL_METHOD="install" GO_TOOL_VENDOR=true install_go_tool "\${proto_go_tools[@]}"
```
Not from vendors dir:
```
GO_TOOL_METHOD="install" install_go_tool "github.com/local/path/of/tool"
```

Adds ability to install go tools NOT from vendor/

---

dot-studio/golang

Even if we don't run `dep ensure` we still want to run `go build`, that is the main purpose of this function.

Fix go_build studio helper

---

dot-studio/habitat_overrides
dot-studio/logging

Alright, Friends!!! It is time to bring some color to the Studio!!
This PR adds a series of helper methods to log:
- `log_line` Logs a line, just like `build_line` from a habitat build plan.
- `warn` Logs a WARN message.
- `error` Logs an ERROR message.
After this PR gets merge I will work on updating our logs so that they look similar to this:
We also define a few helper functions that are only available when habitat builds a package, this is primarily to support scaffolding callbacks.

Adds colors and logging helpers to studio

---

buildkite-agent-hooks/update-utilities.sh

Expeditor is a release engineering utility used by Chef. 

Install/upgrade Expeditor CLI as part of normal routine

---

README.md
bin/check-rpm-signed
bin/install-omnibus-product

These scripts will help simplify omnibus project test scripts that will be used when tests are run in buildkite infrastructure instead of jenkins infrastructure.

Add check-rpm-signed and install-omnibus-product scripts

---

bin/install-buildkite-agent

This allows us to update the hooks without having to rebuild the AMI.

Source the hook files rather than including them in the hook file

---

dot-studio/svc_coord

The output of hab svc status changed.
The third column is now the desired state instead of the state, so
a few functions need to be updated.

hab svc status changes fallout

---

buildkite-agent-hooks/update-utilities.sh

This should hopefully prevent any 'hab pkg' installation issues caused
by simultaneous package installs.

Add flock around Expeditor CLI install

---

dot-studio/studio_setup

For projects that don't regularly need a GITHUB_TOKEN in their studio,
this forces a dependency that can be in the best case annoying and
problematic for CI.

Don't fail on missing GITHUB_TOKEN

---

bin/install-omnibus-product

mixlib-install should be responsible for encoding when necessary.

Remove url encoding of "+" in version in install-omnibus-product

---

bin/install-habitat

Trying to allow a non-root user to the correct `/hab` directories is impossible. If we're running a service `/hab/svc/foo` that has certain requirements on file permissions, this script would nuke those. 
The `install-script` script should stop with simply adding the sudo privileges.

Require 'sudo' be used with 'hab' binary

---

.expeditor/config.yml
.expeditor/verify.pipeline.yml
bin/install-habitat

Fully match parameter support for install-habitat. Specifically, allow us to specify the install target.

Add matching parameter support for install-habitat

---

buildkite-agent-hooks/expeditor.sh

Right now, we install the Expeditor CLI as part of the pre-checkout hook, and run the secrets and account setup commands as part of the command itself. By putting all of this into the environment hook, we can avoid having to muck with the commands given to us and instead allow secrets to be safely accessed from anywhere. 
The recommended use would be to add the following line to the bootstrap script of a Buildkite Queue:
```
install-buildkite-agent hook environment expeditor
```

Add Expeditor environment hook

---

buildkite-agent-hooks/expeditor.sh

* Set `HAB_NONINTERACTIVE=true` to prevent log overflow due to interactive elements of downloading hab packages. 
* Modify bash logic to not panic when `EXPEDITOR_*` environment variables are missing. 

Fix minor issues in Expeditor Hook

---

buildkite-agent-hooks/expeditor.sh
buildkite-agent-hooks/update-utilities.sh

We had the former set in the new expeditor.sh hook but not in the
still-in-use update-utilities.sh script.

Set HAB_NONINTERACTIVE and HAB_NOCOLORING

---

buildkite-agent-hooks/expeditor.sh

When we have multiple agents on an instance, we can get contention between certain actions. This avoids that by putting all Expeditor setup actions under the flock. 

Move all Expeditor actions under the flock

---

dot-studio/golang

Chef automate has some makefiles that assume gofmt is in the PATH, and I would assume `setup_go_workspace` would make all the golang things work.
N/A

Install gofmt when we install go.

---

README.md
bin/check-omnibus-package-signed

This utility makes it easy to verify that an
rpm has been signed or that a dmg contains a
signed package file.
This replaces functionality of the check-rpm-signed utility.
https://github.com/chef/release-engineering/issues/569

Add check-omnibus-package-signed utility

---

bin/install-habitat

This can cause weird log grouping behavior in Buildkite, especially
when used in the `docker` Expeditor executor.

Do not prefix output with '---'

---

buildkite-agent-hooks/expeditor.sh
buildkite-agent-hooks/update-utilities.sh

`sudo -E` preserves the callers environment. In this case, our
environment includes `HAB_NONINTERACTIVE` and `HAB_NOCOLORING` which
prevents hundreds of log lines in CI logs.

Use `sudo -E` when calling `hab pkg install`

---

bin/aws-configure
bin/ceval
bin/citadel
bin/configure-github-account
bin/hab-origin
bin/hab-verify

These tools are no longer required due to new functionality with Buildkite+Expeditor.

Mark subset of tooling as deprecated

---

studio-common/dot-studio/hab_toolchain

Use correct sub-shell statement in hab_toolchain helpers. 
Before this change, if you use the helper `install` you will end up in a different path
from where you started the helper.
```
[2][default:/src:0]# install
[3][default:/:0]#
```
By using the correct sub-shelling statement in these helpers we no longer changing
directories and therefore, we don't have the above issue anymore.

Use correct sub-shell statement

---

go.mod
go.sum
vault-util/cmd/print-git-credentials.go

The way this utility was previously designed, it would create a fresh
installation token on every git request, which could be more than 1 per
second. That would essentially create one token for every git request,
which is not what we want.
This design will create a token and save it to disk. We'll then read
the token from disk if it exists and is unexpired, otherwise we'll
create a fresh token.
We are writing the token to disk in plaintext, but it is a temporary
token. Given the current usage patterns, it's an acceptable trade off
at the moment. In the future, if we become more concerned, we can store
the token encrypted. However, we store AWS credentials in plaintext on
disk, so I think we'll be okay.

Cache GitHub token on disk to avoid spamming token creation

---

.expeditor/update_hab_version.sh
.golangci.yml

In the recent rewrite work, the path to the relevant file has changed.

Fix update_hab_version.sh to use correct path

---

cmd/install-habitat/commands/root.go

The Habitat build pipeline changes have broken the automation that is
in place for this.

Bump Habitat to 0.90.6

---

.expeditor/create_release.sh

Using `.` will mess with the contents of the tar and provide a `tar: .: file changed as we read it`. Using the file itself will hopefully avoid that error.

Update tar to exclude tar from the tar itself since it would mess with the directory
