chef/ci-studio-common

README.md
=> Indicate commands need to be run w/ sudo

bin/studio-common
=> Add mechanism to document available helpers

bin/studio-common
=> Missing mkdir

.gitignore, .studiorc, .travis.yml, Makefile, README.md, bin/hab-origin, bin/hab-verify, bin/install-tool, bin/run-if-changed, habitat/plan.sh, install.sh, lib/a_core, lib/hab_toolchain, lib/integration_testing, lib/networking, lib/studio_setup, lib/svc_coord, lib/z_core, tools/aws.sh, tools/hab.sh, tools/terraform.sh
=> Expand upon ci-studio-common functionality

tools/terraform.sh
=> Update terraform tool definition to fix install error

README.md, lib/a_core
=> Fix loading of helpers in non-CI environments

README.md
=> Clear up some documentation in the README

bin/studio-common
=> Correctly detect whether in CI or not

.expeditor/config.yml
=> Skip markdown-toc for the time being

.expeditor/config.yml, bin/studio-common, dot-studio/hab_toolchain, dot-studio/networking, dot-studio/svc_coord, habitat/plan.sh
=> Lazy-load dependencies rather than loading them at boot

README.md
=> Fix placement of clone-function README example

.studiorc
=> Update install syntax to install hart file

.github/CODEOWNERS, bin/studio-common
=> Only source the plan.sh and default.toml if they exist

README.md, bin/studio-common, dot-studio/hab_toolchain
=> Add 'add_alias' function for using/documenting aliases

bin/studio-common
=> Fix version check warning to show actual installed version

dot-studio/hab_toolchain
Be specific about the actions we will take. 🌮 
Also found a bug where we were not installing the last pkg artifact, now we do! 🎉
=> Fix and Update hab_toolchain install command

.travis.yml, README.md, bin/aws-configure, bin/citadel, bin/hab-origin
=> Add 'aws-configure' and 'citadel' utilities

dot-studio/protobuf
=> New compile_go_protobuf studio helper

.expeditor/update_hab_version.sh, tools/hab.sh
=> Fix incorrect regex preventing hab version from being updated

bin/studio-common
=> Fix typo in studio-common

dot-studio/golang
- Install go when setting up the workspace  …
- New enter_go_workspace to cd into the Go Workspace  …
- New dep_ensure to run dep ensure in the studio  …
=> Golang improvements

.expeditor/config.yml
=> Only take actions when necessary

.travis.yml, tests/tool-test.bats, tools/docker-compose.sh
=> Add docker-compose tool (and tests)

README.md
=> Add documentation about expected environment variables

dot-studio/svc_coord
Fixes https://github.com/chef/ci-studio-common/pull/44
=> Avoid using 'exit' in studio helpers; use 'return'

dot-studio/golang
Because we need to debug sometimes...
=> Adds debugging tools for Go Applications

.github/CODEOWNERS
=> Add @srenatus as a CODEOWNER

bin/run-if-changed
=> Add separate glob pattern to run-if-changed

README.md, bin/ceval, tests/ceval.bats
=> Add ability to conditionally execute certain commands

.expeditor/config.yml, .github/CODEOWNERS
Signed-off-by: Seth Chisamore <schisamo@chef.io>
=> Send all notifications to the JEX team

tools/chefdk/install.sh
=> Exist fast for tools/chefdk.sh

.expeditor/config.yml
Signed-off-by: Seth Chisamore <schisamo@chef.io>
=> Send all notifications to Releng

bin/hab-origin
=> hab-origin improvements

bin/hab-origin
=> Silence grep in hab-origin

.expeditor/verify.pipeline.yml, bin/hab-origin
=> Download the hab origin key if missing

bin/configure-github-account, dot-studio/integration_testing
=> Silence all output for certain commands

README.md, bin/citadel
=> Fix README

.expeditor/config.yml
Signed-off-by: Seth Chisamore <schisamo@chef.io>
=> Auto-delete GitHub branches on merge

.expeditor/config.yml
=> Enable Expeditor for pre-1.0 branch

bin/install-buildkite-agent
=> Set HOME in install-buildkite-agent

bin/ci-studio-common-util, bin/install-habitat
Based largely off http://www.kfirlavi.com/blog/2012/11/06/elegant-locking-of-bash-program/
=> Introduce locking pattern for commands

.gitignore, install.sh
=> Set default install branch to pre-1.0

README.md
=> Fix the pre-1.0 install instructions

dot-studio/golang, dot-studio/hab_toolchain, dot-studio/integration_testing, dot-studio/protobuf, dot-studio/studio_setup, dot-studio/svc_coord
This PR is adopting the new logging helpers to colorize our studio: https://github.com/chef/ci-studio-common/pull/142
It also removes functions that have been deprecated for a while. (months!)
=> Adopt new logging helpers

bin/install-habitat
=> Make sure 'user' has access to root `/hab` directory

.expeditor/verify.pipeline.yml
=> Run studio stuff in docker

bin/install-omnibus-product
=> url encode product_version in install-omnibus-product

buildkite-agent-hooks/update-utilities.sh
=> Only install habitat and run habitat commands on supported architectures

.expeditor/verify.pipeline.yml, bin/aws-configure
* Use default queues
* Update plugin syntax
* Update docker plugin version
=> Update Pipeline Definitions

buildkite-agent-hooks/update-utilities.sh
=> Install the CLI using sudo

.expeditor/update_hab_version.sh
=> Use the new EXPEDITOR_ prefix in script

buildkite-agent-hooks/expeditor.sh
=> Do not source environment variables in subshell

bin/install-omnibus-product
This comment was left accidentally when the url encoding code was removed.
=> Remove comment from install-omnibus-product

.expeditor/build.habitat.yml, .expeditor/config.yml
=> Leverage the new buildkite-based Habitat builds

.expeditor/config.yml, README.md, bin/install-habitat, install.sh
* Update Expeditor config to create 1-stable agent
* Make the default branch `1-stable`
=> Update Expeditor config for 1-stable

install.ps1, install.sh
=> Make install.(sh|ps1) install working versions

buildkite-agent-hooks/ci-studio-common.bat, buildkite-agent-hooks/ci-studio-common.ps1, buildkite-agent-hooks/ci-studio-common.sh
This provides a more stable run-time environment.
=> Remove auto update in ci-studio-common hooks

.expeditor/artifact_upload.sh, .expeditor/go_build.pipeline.yml
Need double quotes around the content to be uploaded.
=> Updates to how buildkite-artifact uploads content

.expeditor/create_release.sh
Used amd64 and not x86-64 for arch name
=> Update release to use amd64 and not x86-64

.expeditor/create_release.sh
Directory to where I wanted things downloaded into was ill-formatted 
=> Jfrog dl path had an error

.expeditor/create_release.sh
Fixes the issue where the release would fail due to the file being added multiple times.
=> Updates to fix github release from adding the full zip/tar file multiple times

.expeditor/create_release.sh
Removed tar/zip of all utils as we will be breaking out the utilities unto their own repos
- [x ] Chore (non-breaking change that does not add functionality or fix an issue)
=> Update compression to leave out directory path and just tar/zip the file

.expeditor/create_release.sh
=> Use the last index of array in bash to get util name

.expeditor/create_release.sh
The use of basename simplifies the IFS operator and array splitting
- [ x] Chore (non-breaking change that does not add functionality or fix an issue)
=> Use basename to extract name of util
